# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sqlparse

class Migration(migrations.Migration):

    customViewSQL='''
        CREATE VIEW if NOT EXISTS PictureWithLikesCount AS
        SELECT p.id,
               p.picture,
               p.description,
               p.key,
               p.lastViewTime,
               p.viewCounter,
               p.author_id,
               p.uploadTime,
               CASE WHEN l.like_count IS NULL THEN 0 ELSE l.like_count END as "like_count",
               CASE WHEN d.dislike_count IS NULL THEN 0 ELSE d.dislike_count END as "dislike_count",
               CASE WHEN l.like_count IS NULL THEN 0 ELSE l.like_count END + CASE WHEN d.dislike_count IS NULL THEN 0 ELSE d.dislike_count END as "likes_number"
        FROM Core_picture as p
        LEFT OUTER JOIN
             (
               SELECT picture_id, count() as "like_count"
               FROM Core_likes
               WHERE like=1
               GROUP by picture_id
             ) as l on p.id=l.picture_id
        LEFT OUTER JOIN
             (
               SELECT picture_id, count() as "dislike_count"
               FROM Core_likes
               WHERE like=0
               GROUP by picture_id
             ) as d on p.id=d.picture_id;'''

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureWithLikesCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media_dir/%Y/%m/%d/%S')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('key', models.SlugField(max_length=4, unique=True)),
                ('uploadTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastViewTime', models.DateTimeField(null=True)),
                ('viewCounter', models.PositiveIntegerField(default=0)),
                ('like_count', models.IntegerField()),
                ('dislike_count', models.IntegerField()),
                ('likes_number', models.IntegerField()),
            ],
            options={
                'db_table': 'PictureWithLikesCount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('like', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media_dir/%Y/%m/%d/%S')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('key', models.SlugField(max_length=4, unique=True)),
                ('uploadTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastViewTime', models.DateTimeField(null=True)),
                ('viewCounter', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploadTime'],
            },
        ),
        migrations.AddField(
            model_name='likes',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Picture'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PictureWithLikesCount'
        ),
        migrations.RunSQL(sqlparse.format(customViewSQL, reindent=True, keyword_case='upper'))
        ]
