# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='key',
            field=models.SlugField(default='639M', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='lastViewTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 30, 21, 44, 42, 356145)),
        ),
    ]
