# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 00:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0002_auto_20160730_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='key',
            field=models.SlugField(default='8wGL', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 3, 46, 59, 582833)),
        ),
        migrations.AddField(
            model_name='likes',
            name='picture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Picture'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
