# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 00:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20160731_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='picture_id',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='picture',
            name='key',
            field=models.SlugField(default='Vxcz', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 3, 50, 58, 8914)),
        ),
    ]
